"""Default schedule and events for New Stars Radio (seed + API fallbacks)."""
from __future__ import annotations

from app.schemas.events import StationEvent
from app.schemas.schedule import ScheduleShow

NEW_STARS_SCHEDULE: list[ScheduleShow] = [
    ScheduleShow(
        id=1,
        time="12:00 AM - 5:00 AM",
        show="Overnight Stars Mix",
        dj="Auto DJ",
        description="Non-stop overnight rotation of rising Hip-Hop, R&B, and Smooth Jazz artists.",
        current=False,
    ),
    ScheduleShow(
        id=2,
        time="5:00 AM - 7:00 AM",
        show="Sunrise Smooth Jazz",
        dj="DJ Marcus",
        description="Ease into the day with mellow jazz and soulful instrumentals.",
        current=False,
    ),
    ScheduleShow(
        id=3,
        time="7:00 AM - 10:00 AM",
        show="Morning Hip-Hop Rise",
        dj="DJ Kaya",
        description="Fresh bars and beats from tomorrow's stars — news and community shout-outs.",
        current=False,
    ),
    ScheduleShow(
        id=4,
        time="10:00 AM - 2:00 PM",
        show="Midday R&B Flow",
        dj="DJ Lila",
        description="Midday grooves and new voices in R&B — perfect for work or the road.",
        current=False,
    ),
    ScheduleShow(
        id=5,
        time="2:00 PM - 6:00 PM",
        show="Afternoon Discovery",
        dj="New Stars Team",
        description="Deep cuts and debut tracks from unsigned artists we're breaking first.",
        current=False,
    ),
    ScheduleShow(
        id=6,
        time="6:00 PM - 9:00 PM",
        show="Drive Time Heat",
        dj="DJ Apex",
        description="Peak-hour energy — Hip-Hop and R&B anthems for the commute home.",
        current=False,
    ),
    ScheduleShow(
        id=7,
        time="9:00 PM - 12:00 AM",
        show="Late Night Lounge",
        dj="DJ Nova",
        description="Smooth Jazz and slow R&B to wind down the evening.",
        current=False,
    ),
]

NEW_STARS_EVENT_LOCATIONS: list[str] = [
    "Windhoek",
    "Cape Town",
    "Johannesburg",
    "Online Livestream",
]

NEW_STARS_EVENTS: list[StationEvent] = [
    StationEvent(
        id=1,
        title="New Stars Street Sessions",
        date_label="Sat, Jun 21 - 7:00 PM",
        location="Freedom Plaza, Windhoek",
        is_online=False,
        is_this_week=True,
        status="upcoming",
        description="Live sets from local up-and-comers, radio merch table, and on-air interviews.",
        starts_at="2026-06-21T19:00:00+02:00",
        ends_at="2026-06-21T22:00:00+02:00",
        image_url="https://picsum.photos/seed/newstars-street-sessions/800/450",
        country_code=None,
    ),
    StationEvent(
        id=2,
        title="Artist Spotlight Live",
        date_label="Sun, Jun 22 - 4:00 PM",
        location="Online Livestream",
        is_online=True,
        is_this_week=True,
        status="upcoming",
        description="Watch rising artists perform and take listener questions in real time.",
        starts_at="2026-06-22T16:00:00+02:00",
        ends_at="2026-06-22T18:00:00+02:00",
        image_url="https://picsum.photos/seed/newstars-spotlight-live/800/450",
        country_code=None,
    ),
    StationEvent(
        id=3,
        title="Cape Town Listener Meetup",
        date_label="Fri, Jun 27 - 6:30 PM",
        location="V&A Waterfront Amphitheatre, Cape Town",
        is_online=False,
        is_this_week=True,
        status="upcoming",
        description="Meet the team, hear unreleased tracks, and connect with other New Stars listeners.",
        starts_at="2026-06-27T18:30:00+02:00",
        ends_at="2026-06-27T21:00:00+02:00",
        image_url="https://picsum.photos/seed/newstars-cape-meetup/800/450",
        country_code=None,
    ),
    StationEvent(
        id=4,
        title="Smooth Jazz Sunday",
        date_label="Sun, Jun 29 - 11:00 AM",
        location="Online Livestream",
        is_online=True,
        is_this_week=True,
        status="upcoming",
        description="A laid-back morning of Smooth Jazz discoveries and listener dedications.",
        starts_at="2026-06-29T11:00:00+02:00",
        ends_at="2026-06-29T14:00:00+02:00",
        image_url="https://picsum.photos/seed/newstars-jazz-sunday/800/450",
        country_code=None,
    ),
    StationEvent(
        id=5,
        title="Unsigned Heat Showcase",
        date_label="Sat, Jul 5 - 8:00 PM",
        location="Johannesburg Arts Centre",
        is_online=False,
        is_this_week=False,
        status="upcoming",
        description="Hip-Hop and R&B performers compete for airtime and a featured spot on New Stars Radio.",
        starts_at="2026-07-05T20:00:00+02:00",
        ends_at="2026-07-05T23:30:00+02:00",
        image_url="https://picsum.photos/seed/newstars-unsigned-heat/800/450",
        country_code=None,
    ),
]
